### ISSUE TITLE
getline.c

### ISSUE THREAD

**Issue by alexadeveloper** [alexadeveloper/simple_shell#5]
Write your own version of getline.
julien@ubuntu:~/c/shell$ gcc -Wall -Wextra -Werror -pedantic prompt.c -o prompt
julien@ubuntu:~/c/shell$ ./prompt 
$ cat prompt.c
cat prompt.c
julien@ubuntu:~/c/shell$

**Comment by Fermec28** [comment]
this issue is for advanced task!
